# Generated by Django 5.2.6 on 2025-10-14 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='CI')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes', to='cursos.curso')),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes', to='cursos.kardex')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='KardexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('SER', 'Ser'), ('SABER', 'Saber'), ('HACER', 'Hacer'), ('DECIDIR', 'Decidir')], max_length=10)),
                ('descripcion', models.CharField(max_length=160)),
                ('sentido', models.CharField(choices=[('NEGATIVO', 'Negativo'), ('POSITIVO', 'Positivo')], default='NEGATIVO', max_length=10)),
            ],
            options={
                'verbose_name': 'ítem de kárdex',
                'verbose_name_plural': 'ítems de kárdex',
                'constraints': [models.UniqueConstraint(fields=('area', 'descripcion'), name='uq_kdx_item')],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('ATRASO', 'Atraso')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'indexes': [models.Index(fields=['fecha'], name='estudiantes_fecha_f74fe3_idx')],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'fecha'), name='uq_asistencia_dia')],
            },
        ),
        migrations.CreateModel(
            name='KardexRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('sello_maestro', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_kardex', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_registros', to='estudiantes.estudiante')),
                ('kardex_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estudiantes.kardexitem')),
            ],
            options={
                'verbose_name': 'registro de kárdex',
                'verbose_name_plural': 'registros de kárdex',
                'ordering': ['fecha', 'hora', 'id'],
                'indexes': [models.Index(fields=['estudiante', 'fecha'], name='estudiantes_estudia_3e7384_idx'), models.Index(fields=['kardex_item'], name='estudiantes_kardex__674fef_idx')],
            },
        ),
    ]
