# Generated by Django 5.2.6 on 2025-11-03 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asis_cal_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendario de asistencia',
                'verbose_name_plural': 'calendarios de asistencia',
                'ordering': ['-activo', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='CI')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='cursos.curso')),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes', to='cursos.kardex')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='KardexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('SER', 'SER'), ('SABER', 'SABER'), ('HACER', 'HACER'), ('DECIDIR', 'DECIDIR')], max_length=16, verbose_name='Área')),
                ('descripcion', models.CharField(max_length=160, verbose_name='Descripción')),
                ('sentido', models.CharField(choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], default='NEGATIVO', max_length=16, verbose_name='Sentido')),
                ('peso', models.PositiveSmallIntegerField(default=10, help_text='Severidad base: p.ej., 5 (leve), 10 (mod.), 20 (import.), 35 (grave).', verbose_name='Peso (severidad)')),
                ('ventana_dias', models.PositiveSmallIntegerField(default=14, help_text='Período para contar recurrencias del mismo ítem.', verbose_name='Ventana (días)')),
                ('umbral', models.PositiveSmallIntegerField(default=0, help_text='Cantidad dentro de la ventana para disparar citación (0 = sin acumulación).', verbose_name='Umbral (repeticiones)')),
                ('directa', models.BooleanField(default=False, help_text='Si es True, un solo evento crea citación (Abierta).', verbose_name='Citación directa')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'ítem de kárdex',
                'verbose_name_plural': 'ítems de kárdex',
                'ordering': ['area', 'descripcion'],
                'indexes': [models.Index(fields=['area', 'sentido', 'activo'], name='estudiantes_area_fea613_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones', to='estudiantes.asistenciacalendario')),
            ],
            options={
                'verbose_name': 'exclusión de asistencia',
                'verbose_name_plural': 'exclusiones de asistencia',
                'ordering': ['fecha'],
                'unique_together': {('calendario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('ATRASO', 'Atraso')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['-fecha', 'estudiante_id'],
                'indexes': [models.Index(fields=['fecha'], name='estudiantes_fecha_f74fe3_idx'), models.Index(fields=['estudiante', 'fecha'], name='estudiantes_estudia_dba588_idx')],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'fecha'), name='uq_asistencia_dia')],
            },
        ),
        migrations.CreateModel(
            name='KardexRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('sello_maestro', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_kardex', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_registros', to='estudiantes.estudiante')),
                ('kardex_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estudiantes.kardexitem')),
            ],
            options={
                'verbose_name': 'registro de kárdex',
                'verbose_name_plural': 'registros de kárdex',
                'ordering': ['fecha', 'hora', 'id'],
                'indexes': [models.Index(fields=['estudiante', 'fecha'], name='estudiantes_estudia_3e7384_idx'), models.Index(fields=['kardex_item'], name='estudiantes_kardex__674fef_idx')],
            },
        ),
    ]
