# Generated by Django 5.2.6 on 2025-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kardexitem',
            constraint=models.UniqueConstraint(fields=('area', 'descripcion'), name='uq_kdx_item'),
        ),
    ]
