# Generated by Django 5.2.6 on 2025-10-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_estudiante_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha', 'estudiante_id'], 'verbose_name': 'asistencia', 'verbose_name_plural': 'asistencias'},
        ),
        migrations.AddIndex(
            model_name='asistencia',
            index=models.Index(fields=['estudiante', 'fecha'], name='estudiantes_estudia_dba588_idx'),
        ),
    ]
