# Generated by Django 5.2.6 on 2025-10-30 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_alter_asistencia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asis_cal_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'calendario de asistencia',
                'verbose_name_plural': 'calendarios de asistencia',
                'ordering': ['-activo', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones', to='estudiantes.asistenciacalendario')),
            ],
            options={
                'verbose_name': 'exclusión de asistencia',
                'verbose_name_plural': 'exclusiones de asistencia',
                'ordering': ['fecha'],
                'unique_together': {('calendario', 'fecha')},
            },
        ),
    ]
