# Generated by Django 5.2.6 on 2025-11-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_kardexitem_reglas_y_timestamps'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kardexitem',
            name='estudian_kdx_idx',
        ),
    ]
