# Generated by Django 5.2.6 on 2025-11-03 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('in_app', 'En la aplicación')], default='in_app', max_length=16, verbose_name='Canal')),
                ('titulo', models.CharField(max_length=140, verbose_name='Título')),
                ('cuerpo', models.TextField(blank=True, default='', verbose_name='Cuerpo')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('enviada_en', models.DateTimeField(auto_now_add=True, verbose_name='Enviada en')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Leída en')),
                ('citacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='citaciones.citacion', verbose_name='Citación relacionada')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destino')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-enviada_en'],
                'indexes': [models.Index(fields=['usuario_destino', 'leida'], name='notificacio_usuario_90bc4e_idx'), models.Index(fields=['enviada_en'], name='notificacio_enviada_53c034_idx')],
            },
        ),
    ]
