# Generated by Django 5.2.6 on 2025-10-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citaciones', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('estado_entrega', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADA', 'Entregada'), ('LEIDA', 'Leida'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10)),
                ('ts_creacion', models.DateTimeField(auto_now_add=True)),
                ('ts_entrega', models.DateTimeField(blank=True, null=True)),
                ('ts_lectura', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='citaciones.citacion')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='notificaciones', to='cuentas.usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'indexes': [models.Index(fields=['receptor', 'estado_entrega', 'ts_creacion'], name='notificacio_recepto_b99969_idx'), models.Index(fields=['citacion'], name='notificacio_citacio_0d86ba_idx')],
            },
        ),
    ]
