# Generated by Django 5.2.6 on 2025-11-03 21:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0), verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(default=datetime.time(12, 0), verbose_name='Hora de fin')),
                ('minutos_por_slot', models.PositiveSmallIntegerField(default=15, verbose_name='Minutos por slot')),
                ('duracion_por_defecto', models.PositiveSmallIntegerField(default=30, verbose_name='Duración por defecto (min)')),
                ('max_dias', models.PositiveSmallIntegerField(default=7, verbose_name='Días máximos para agendar')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'configuración de atención',
                'verbose_name_plural': 'configuraciones de atención',
            },
        ),
        migrations.CreateModel(
            name='MotivoCitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('area', models.CharField(choices=[('SER', 'Ser'), ('SABER', 'Saber'), ('HACER', 'Hacer'), ('DECIDIR', 'Decidir')], max_length=7)),
                ('descripcion', models.CharField(max_length=200)),
                ('severidad_default', models.PositiveSmallIntegerField()),
                ('peso_prioridad_default', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'motivo de citación',
                'verbose_name_plural': 'motivos de citación',
            },
        ),
        migrations.CreateModel(
            name='ReglaTransversalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('umbral', models.PositiveSmallIntegerField(default=35, verbose_name='Umbral de suma')),
                ('ventana_dias', models.PositiveSmallIntegerField(default=14, verbose_name='Ventana (días)')),
                ('programada', models.BooleanField(default=False, verbose_name='Programada')),
                ('vigente_desde', models.DateTimeField(blank=True, null=True, verbose_name='Vigente desde')),
                ('historial_json', models.TextField(blank=True, default='[]', verbose_name='Historial (JSON)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'configuración de regla transversal',
                'verbose_name_plural': 'configuraciones de regla transversal',
            },
        ),
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_resumen', models.CharField(blank=True, default='', max_length=160, verbose_name='Motivo (resumen)')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta (borrador)'), ('AGENDADA', 'Agendada'), ('NOTIFICADA', 'Notificada a padres/tutores'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=12, verbose_name='Estado')),
                ('duracion_min', models.PositiveSmallIntegerField(default=30, help_text='15, 30, 45 o 60. Se usa para agenda y métricas.', verbose_name='Duración (minutos)')),
                ('aprobado_en', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado en')),
                ('fecha_citacion', models.DateField(blank=True, null=True, verbose_name='Fecha de citación')),
                ('hora_citacion', models.TimeField(blank=True, null=True, verbose_name='Hora de citación')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citaciones', to='estudiantes.estudiante', verbose_name='Estudiante')),
                ('kardex_registro', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='citacion_origen', to='estudiantes.kardexregistro', verbose_name='Registro de Kárdex')),
            ],
            options={
                'verbose_name': 'citación',
                'verbose_name_plural': 'citaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('EN_SERVICIO', 'En servicio'), ('ATENDIDA', 'Atendida'), ('FALLIDA', 'Fallida')], default='EN_COLA', max_length=12, verbose_name='Estado en cola')),
                ('llegada_en', models.DateTimeField(auto_now_add=True, verbose_name='Llegó a la cola')),
                ('inicio_servicio_en', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de atención')),
                ('fin_servicio_en', models.DateTimeField(blank=True, null=True, verbose_name='Fin de atención')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('citacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='citaciones.citacion', verbose_name='Citación')),
            ],
            options={
                'verbose_name': 'ítem de cola',
                'verbose_name_plural': 'ítems de cola',
                'ordering': ['llegada_en'],
            },
        ),
        migrations.CreateModel(
            name='CitacionMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_motivo', to='citaciones.citacion')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='citaciones.motivocitacion')),
            ],
            options={
                'verbose_name': 'detalle de motivo',
                'verbose_name_plural': 'detalles de motivos',
                'constraints': [models.UniqueConstraint(fields=('citacion', 'motivo'), name='uq_cit_mot')],
            },
        ),
    ]
