# Generated by Django 5.2.6 on 2025-10-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoCitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('area', models.CharField(choices=[('SER', 'Ser'), ('SABER', 'Saber'), ('HACER', 'Hacer'), ('DECIDIR', 'Decidir')], max_length=7)),
                ('descripcion', models.CharField(max_length=200)),
                ('severidad_default', models.PositiveSmallIntegerField()),
                ('peso_prioridad_default', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'motivo de citación',
                'verbose_name_plural': 'motivos de citación',
            },
        ),
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('CONDUCTA', 'Conducta'), ('ACADEMICO', 'Academico')], max_length=12)),
                ('severidad', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('NOTIFICADA', 'Notificada'), ('AGENDADA', 'Agendada'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=12)),
                ('fecha_citacion', models.DateField(blank=True, null=True)),
                ('hora_citacion', models.TimeField(blank=True, null=True)),
                ('flag_falta', models.BooleanField(default=False)),
                ('flag_atraso', models.BooleanField(default=False)),
                ('flag_no_tarea', models.BooleanField(default=False)),
                ('puntaje_motivos', models.IntegerField(default=0)),
                ('recurrencia_30d', models.IntegerField(default=0)),
                ('impulso_manual', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_objetivo', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='citaciones_creadas', to='cuentas.usuario')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citaciones', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'citación',
                'verbose_name_plural': 'citaciones',
            },
        ),
        migrations.CreateModel(
            name='CitacionMotivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_motivo', to='citaciones.citacion')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='citaciones.motivocitacion')),
            ],
            options={
                'verbose_name': 'detalle de motivo',
                'verbose_name_plural': 'detalles de motivos',
                'constraints': [models.UniqueConstraint(fields=('citacion', 'motivo'), name='uq_cit_mot')],
            },
        ),
    ]
