# Generated by Django 5.2.6 on 2025-11-26 00:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0004_remove_kardexitem_estudian_kdx_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Ingreso al sistema'), ('LOGOUT', 'Salida del sistema'), ('CREAR', 'Creación de estudiante'), ('EDITAR', 'Edición de estudiante'), ('ELIMINAR', 'Eliminación de estudiante'), ('REPORTE', 'Reporte generado'), ('OTRO', 'Otra acción')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('estudiante', models.ForeignKey(blank=True, help_text='Estudiante sobre el que se realizó la acción (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='estudiantes.estudiante')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_estudiantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_studentlog',
                'ordering': ['-creado_en'],
            },
        ),
    ]
