# Generated by Django 5.2.6 on 2025-11-26 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
        ('estudiantes', '0004_remove_kardexitem_estudian_kdx_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlog',
            name='accion',
            field=models.CharField(choices=[('CREAR', 'Creación'), ('EDITAR', 'Modificación'), ('ELIMINAR', 'Eliminación')], max_length=15),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='estudiante',
            field=models.ForeignKey(blank=True, help_text='Estudiante sobre el que se realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='estudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='studentlog',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_estudiantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
