# Generated by Django 5.2.6 on 2025-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_studentlog_accion_alter_studentlog_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='estudiante_nombre',
            field=models.CharField(blank=True, help_text='Nombre del estudiante en el momento de la acción', max_length=255),
        ),
    ]
